// <auto-generated />
using ExamWeb_NguyenThanhSon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_NguyenThanhSon.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeb_LeVanTeo.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NGheSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 10,
                            TuaCD = "CD Nỗi buồn gác trọ"
                        },
                        new
                        {
                            Id = 2,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 15,
                            TuaCD = "CD Bài ca tình đêm"
                        },
                        new
                        {
                            Id = 3,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 10,
                            TuaCD = "CD BABYMONSTER"
                        },
                        new
                        {
                            Id = 4,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 15,
                            TuaCD = "CD Chuyện chúng mình"
                        },
                        new
                        {
                            Id = 5,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 10,
                            TuaCD = "CD Today US-UK Hit"
                        },
                        new
                        {
                            Id = 6,
                            NGhesi = "A",
                            Giaban = 12000.0,
                            SoLuong = 15,
                            TuaCD = "CD Đoá hồng nhạc việt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
